---
dist: bionic
sudo: required
group: edge
services: docker
arch:
  - amd64
  - arm64
language: python
python: 3.8
env:
  - SCENARIO=allinone-ubuntu18.04
install: pip install ansible molecule docker-py pre-commit pylint pep257 yamllint ansible-lint pytest testinfra
script:
  - pushd .. && ln -s ansible-pacifica pacifica.ansible_pacifica && popd
  - python molecule/gen-scenarios.py
  - molecule test -s $SCENARIO
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
